const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");

const root=path.resolve(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const app=read("app.js");
const html=read("index.html");
const worker=read("service-worker.js");
const style=read("style.css");
const backlog=read("BACKLOG.md");

assert.match(app,/version:"12\.4\.0"/);
assert.match(app,/schemaVersion:8/);
assert.match(app,/const ROUTINES_KEY="dailyRoutineRoutines\.v12"/);
assert.match(app,/const PROGRESS_KEY="dailyRoutineProgress\.v12"/);
assert.match(app,/const STEP_STATE_KEY="dailyRoutineStepState\.v12"/);
assert.match(app,/const STEP_OVERRIDE_KEY="dailyRoutineStepOverrides\.v12"/);
assert.match(app,/const PRIORITY_KEY="dailyRoutineStepPriorities\.v12"/);
assert.match(app,/const ROTATIONS_KEY="dailyRoutineRotations\.v12"/);
assert.match(app,/const ROUTINE_STARTS_KEY="dailyRoutineStarts\.v12"/);
assert.match(app,/const STEP_REPEATS_KEY="dailyRoutineStepRepeats\.v12"/);
assert.match(app,/function migrateLegacyData\(\)/);
assert.match(app,/localStorage\.getItem\(ROUTINES_KEY\)!==null/);
assert.match(app,/LEGACY_HABITS_KEY/);
assert.match(app,/LEGACY_COMPLETIONS_KEY/);
assert.match(app,/LEGACY_BLOCKS_KEY/);
assert.match(app,/LEGACY_STEPS_KEY/);
assert.match(app,/legacyArchive:legacyArchive\(\)/);
assert.match(app,/Retires repeat counters/);
assert.match(app,/function normalizeRoutine/);
assert.match(app,/lockSteps:routine\.lockSteps!==false/);
assert.match(app,/startMode:routine\.startMode==="manual"\?"manual":"automatic"/);
assert.match(app,/repeatable:step&&step\.repeatable===true/);
assert.match(app,/function sortRoutines/);
assert.match(app,/function dueRoutinesOn/);
assert.match(app,/todayRoutineSwitch/);
assert.match(app,/fromRoutineId,toRoutineId/);
assert.match(app,/function visibleStepsForDate/);
assert.match(app,/function claimPriorityCarryoversForDate/);
assert.match(app,/function visiblePriorityStepsForDate/);
assert.match(app,/function togglePriorityNextTime/);
assert.match(app,/function updatePriorityCompletion/);
assert.match(app,/function stepRunsOn/);
assert.match(app,/steps\.filter\(step=>stepRunsOn\(step,dateKey\)\)/);
assert.match(app,/days:days\.length\?days:null/);
assert.match(app,/function firstPendingIndex/);
assert.match(app,/function lastResolvedIndex/);
assert.match(app,/if\(routine\.lockSteps&&index!==firstPendingIndex/);
assert.match(app,/if\(routine\.lockSteps&&index!==lastResolvedIndex/);
assert.match(app,/all\[dateKey\]\[routine\.id\]\[stepId\]=status/);
assert.match(app,/state:"done"/);
assert.match(app,/skippedSteps:summary\.skipped/);
assert.match(app,/function pauseRoutine/);
assert.match(app,/function resumeRoutine/);
assert.match(app,/confirm\('Pause "'\+routine\.name/);
assert.match(app,/confirm\('Resume "'\+routine\.name/);
assert.match(app,/\?\\n\\nIt will/);
assert.doesNotMatch(app,/\\\\n\\\\n/);
assert.match(app,/class="routine-step-check/);
assert.match(app,/class="step-skip-btn/);
assert.match(app,/class="step-priority-btn/);
assert.match(app,/priority-step-pill/);
assert.doesNotMatch(app,/step-undo-btn/);
assert.match(app,/function pendingMatchingSteps/);
assert.match(app,/function applyTodayStepReplacement/);
assert.match(app,/function replaceRemainingStepsForToday/);
assert.match(app,/class="step-replace-btn/);
assert.match(app,/temporary-step-pill/);
assert.match(app,/stepOverrides:loadStepOverrides\(\)/);
assert.match(app,/stepPriorities:loadPriorityCarryovers\(\)/);
assert.match(app,/rotations:loadRotations\(\)/);
assert.match(app,/routineStarts:loadRoutineStarts\(\)/);
assert.match(app,/stepRepeats:loadStepRepeats\(\)/);
assert.match(app,/function repeatStepForToday/);
assert.match(app,/function routineReadyToComplete/);
assert.match(app,/function completeRoutineForToday/);
assert.match(app,/getStepState\(dateKey,routine\.id,stepId\)!=="done"/);
assert.match(app,/class="primary-btn complete-routine-btn"/);
assert.match(app,/Finish this routine and unlock the next one/);
assert.match(app,/function visibleRepeatStepsForDate/);
assert.match(app,/Can repeat at the bottom today/);
assert.match(app,/class="step-repeat-btn/);
assert.match(app,/function isRoutineStarted/);
assert.match(app,/function startRoutineForToday/);
assert.match(app,/class="primary-btn start-routine-btn"/);
assert.match(app,/function rotateSubstep/);
assert.match(app,/function duplicateEditorStep/);
assert.match(app,/function requestRemoveEditorStep/);
assert.match(app,/function askMatchAction/);
assert.match(app,/Apply & Link All Matches/);
assert.match(app,/Array\.isArray\(parsed\.stepPriorities\)/);
assert.match(app,/clearExpiredStepOverrides\(\)/);
assert.match(app,/function currentRoutineForDate/);
assert.match(app,/className="routine-card "/);
assert.match(app,/current-routine/);
assert.match(app,/locked-routine/);
assert.match(app,/routineLocked\|\|waitingToStart\?true:isCurrent\?false/);
assert.match(app,/manuallyCollapsed\[routine\.id\]=isRoutineResolved/);
assert.match(app,/function createRecoverySnapshot/);
assert.match(app,/function importBackupPayload/);
assert.match(app,/Array\.isArray\(parsed\.routines\)/);
assert.match(app,/Array\.isArray\(parsed\.habits\)/);
assert.match(app,/updateViaCache:"none"/);
assert.match(app,/Installing Update…/);
assert.match(app,/Open Updated Version/);
assert.match(app,/ACTIVATE_AFTER_BACKUP/);
assert.match(app,/const sameWaitingUpdate=waitingServiceWorker===worker&&!E\.updateSheet\.classList\.contains\("hidden"\)/);
assert.match(app,/if\(sameWaitingUpdate\)return/);

assert.match(html,/id="routineList"/);
assert.match(html,/id="todayProgressText"/);
assert.match(html,/id="todayRoutineSwitchFrom"/);
assert.match(html,/id="todayRoutineSwitchTo"/);
assert.match(html,/id="allRoutines"/);
assert.match(html,/id="autoCollapseRoutines"/);
assert.match(html,/id="routineForm"/);
assert.match(html,/id="lockSteps"/);
assert.match(html,/id="routineStartMode"/);
assert.match(html,/Wait until I start it/);
assert.match(html,/Complete steps in order/);
assert.match(html,/Duplicate steps stay separate/);
assert.match(html,/Each step can run every routine day or only on selected weekdays/);
assert.doesNotMatch(html,/id="timeBlocks"/);
assert.doesNotMatch(html,/id="occurrenceBlocks"/);
assert.doesNotMatch(html,/Target \/ cutoff time/);

for(const asset of ["manifest.json","style.css","app.js"]){
  assert.match(html,new RegExp(asset.replace(".","\\.")+"[?]v=12\\.4\\.0"));
}

assert.match(worker,/CACHE_NAME="daily-routine-v12-4-0"/);
assert.match(worker,/const RELEASE_META=\{version:"12\.4\.0"/);
assert.match(worker,/Moves Repeat to completed steps/);
assert.match(worker,/Resolving every step now shows Complete Routine/);
assert.match(worker,/UPDATE_GATE_BOOTSTRAP=false/);
assert.match(worker,/if\(UPDATE_GATE_BOOTSTRAP\)self\.skipWaiting\(\)/);
assert.match(worker,/ACTIVATE_AFTER_BACKUP/);
assert.match(worker,/event\.request\.mode==="navigate"/);
assert.match(worker,/fetch\(event\.request,\{cache:"no-store"\}\)/);
assert.match(worker,/GET_RELEASE_META/);
assert.doesNotMatch(worker,/11\.1\.6/);

assert.match(style,/\.routine-list\{/);
assert.match(style,/\.routine-card\{/);
assert.match(style,/\.routine-step-row\.locked/);
assert.match(style,/\.step-rotation-today/);
assert.match(style,/\.rotation-editor/);
assert.match(style,/\.routine-step-row\.skipped/);
assert.match(style,/\.routine-step-check\{/);
assert.match(style,/min-height:30px/);
assert.match(style,/\.step-skip-btn\{/);
assert.match(style,/\.step-priority-btn\{/);
assert.match(style,/\.priority-step-pill\{/);
assert.match(style,/\.routine-step-row\.priority-step\{/);
assert.match(style,/\.review-priority-btn\{/);
assert.match(style,/\.step-replace-btn\{/);
assert.match(style,/\.temporary-step-pill\{/);
assert.match(style,/\.routine-card\.current-routine\{/);
assert.match(style,/\.routine-card\.locked-routine\{/);
assert.match(style,/\.routine-card\.waiting-routine\{/);
assert.match(style,/\.routine-start-panel/);
assert.match(style,/\.routine-finish-panel\{/);
assert.match(style,/\.step-repeat-btn\{/);
assert.match(style,/\.repeat-step-pill\{/);
assert.match(style,/\.step-repeat-editor\{/);
assert.match(style,/\.routine-step-row\.temporary-repeat-step\{border-color:rgba\(110,231,183,\.35\);background:rgba\(16,185,129,\.09\)\}/);
assert.match(style,/\.routine-card-header:disabled\{/);
assert.match(style,/\.step-schedule-editor\{/);
assert.match(style,/\.step-day-buttons button\.selected\{/);
assert.match(style,/\.step-day-buttons\.hidden\{display:none\}/);
assert.doesNotMatch(style,/\.step-undo-btn/);
assert.match(style,/\.skip-review-details\.hidden\{display:none\}/);
assert.match(style,/max-height:calc\(100dvh - 36px\)/);
assert.match(style,/overflow-y:auto/);

assert.match(backlog,/v12\.4\.0 — Repeat After Completion & Manual Routine Finish/);
assert.match(backlog,/v12\.3\.1 — Repeat Step Name Visibility/);
assert.match(backlog,/v12\.3\.0 — Repeat a Step at the Bottom/);
assert.match(backlog,/v12\.0\.8 — Priority Next Routine/);
assert.match(backlog,/Household accounts and sharing/);
assert.match(backlog,/Retire repeat counters/);

console.log("Safe update and manual routine completion assertions passed for v12.4.0");
