const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");

const root=path.resolve(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const app=read("app.js");
const html=read("index.html");
const worker=read("service-worker.js");
const style=read("style.css");
const backlog=read("BACKLOG.md");

assert.match(app,/version:"12\.0\.4"/);
assert.match(app,/schemaVersion:8/);
assert.match(app,/const ROUTINES_KEY="dailyRoutineRoutines\.v12"/);
assert.match(app,/const PROGRESS_KEY="dailyRoutineProgress\.v12"/);
assert.match(app,/const STEP_STATE_KEY="dailyRoutineStepState\.v12"/);
assert.match(app,/const STEP_OVERRIDE_KEY="dailyRoutineStepOverrides\.v12"/);
assert.match(app,/function migrateLegacyData\(\)/);
assert.match(app,/localStorage\.getItem\(ROUTINES_KEY\)!==null/);
assert.match(app,/LEGACY_HABITS_KEY/);
assert.match(app,/LEGACY_COMPLETIONS_KEY/);
assert.match(app,/LEGACY_BLOCKS_KEY/);
assert.match(app,/LEGACY_STEPS_KEY/);
assert.match(app,/legacyArchive:legacyArchive\(\)/);
assert.match(app,/Retires repeat counters/);
assert.match(app,/function normalizeRoutine/);
assert.match(app,/lockSteps:routine\.lockSteps!==false/);
assert.match(app,/function sortRoutines/);
assert.match(app,/function dueRoutinesOn/);
assert.match(app,/todayRoutineSwitch/);
assert.match(app,/fromRoutineId,toRoutineId/);
assert.match(app,/function visibleStepsForDate/);
assert.match(app,/function firstPendingIndex/);
assert.match(app,/function lastResolvedIndex/);
assert.match(app,/if\(routine\.lockSteps&&index!==firstPendingIndex/);
assert.match(app,/if\(routine\.lockSteps&&index!==lastResolvedIndex/);
assert.match(app,/all\[dateKey\]\[routine\.id\]\[stepId\]=status/);
assert.match(app,/state:"done"/);
assert.match(app,/skippedSteps:summary\.skipped/);
assert.match(app,/function pauseRoutine/);
assert.match(app,/function resumeRoutine/);
assert.match(app,/confirm\('Pause "'\+routine\.name/);
assert.match(app,/confirm\('Resume "'\+routine\.name/);
assert.match(app,/\?\\n\\nIt will/);
assert.doesNotMatch(app,/\\\\n\\\\n/);
assert.match(app,/class="routine-step-check/);
assert.match(app,/class="step-skip-btn/);
assert.doesNotMatch(app,/step-undo-btn/);
assert.match(app,/function pendingMatchingSteps/);
assert.match(app,/function applyTodayStepReplacement/);
assert.match(app,/function replaceRemainingStepsForToday/);
assert.match(app,/class="step-replace-btn/);
assert.match(app,/temporary-step-pill/);
assert.match(app,/stepOverrides:loadStepOverrides\(\)/);
assert.match(app,/clearExpiredStepOverrides\(\)/);
assert.match(app,/function createRecoverySnapshot/);
assert.match(app,/function importBackupPayload/);
assert.match(app,/Array\.isArray\(parsed\.routines\)/);
assert.match(app,/Array\.isArray\(parsed\.habits\)/);
assert.match(app,/updateViaCache:"none"/);
assert.match(app,/Installing Update…/);
assert.match(app,/Open Updated Version/);
assert.match(app,/ACTIVATE_AFTER_BACKUP/);
assert.match(app,/const sameWaitingUpdate=waitingServiceWorker===worker&&!E\.updateSheet\.classList\.contains\("hidden"\)/);
assert.match(app,/if\(sameWaitingUpdate\)return/);

assert.match(html,/id="routineList"/);
assert.match(html,/id="todayProgressText"/);
assert.match(html,/id="todayRoutineSwitchFrom"/);
assert.match(html,/id="todayRoutineSwitchTo"/);
assert.match(html,/id="allRoutines"/);
assert.match(html,/id="autoCollapseRoutines"/);
assert.match(html,/id="routineForm"/);
assert.match(html,/id="lockSteps"/);
assert.match(html,/Complete steps in order/);
assert.match(html,/Duplicate step names are allowed/);
assert.doesNotMatch(html,/id="timeBlocks"/);
assert.doesNotMatch(html,/id="occurrenceBlocks"/);
assert.doesNotMatch(html,/Target \/ cutoff time/);

for(const asset of ["manifest.json","style.css","app.js"]){
  assert.match(html,new RegExp(asset.replace(".","\\.")+"[?]v=12\\.0\\.4"));
}

assert.match(worker,/CACHE_NAME="daily-routine-v12-0-4"/);
assert.match(worker,/const RELEASE_META=\{version:"12\.0\.4"/);
assert.match(worker,/every remaining pending match/);
assert.match(worker,/Completed and skipped matches are left unchanged/);
assert.match(worker,/automatically return to their original names tomorrow/);
assert.match(worker,/no permanent routine or history data is cleared/);
assert.match(worker,/UPDATE_GATE_BOOTSTRAP=false/);
assert.match(worker,/if\(UPDATE_GATE_BOOTSTRAP\)self\.skipWaiting\(\)/);
assert.match(worker,/ACTIVATE_AFTER_BACKUP/);
assert.match(worker,/event\.request\.mode==="navigate"/);
assert.match(worker,/fetch\(event\.request,\{cache:"no-store"\}\)/);
assert.match(worker,/GET_RELEASE_META/);
assert.doesNotMatch(worker,/11\.1\.6/);

assert.match(style,/\.routine-list\{/);
assert.match(style,/\.routine-card\{/);
assert.match(style,/\.routine-step-row\.locked/);
assert.match(style,/\.routine-step-row\.skipped/);
assert.match(style,/\.routine-step-check\{/);
assert.match(style,/min-height:30px/);
assert.match(style,/\.step-skip-btn\{/);
assert.match(style,/\.step-replace-btn\{/);
assert.match(style,/\.temporary-step-pill\{/);
assert.doesNotMatch(style,/\.step-undo-btn/);
assert.match(style,/\.skip-review-details\.hidden\{display:none\}/);
assert.match(style,/max-height:calc\(100dvh - 36px\)/);
assert.match(style,/overflow-y:auto/);

assert.match(backlog,/v12\.0\.4 — Routine-First Redesign/);
assert.match(backlog,/Household accounts and sharing/);
assert.match(backlog,/Retire repeat counters/);

console.log("Safe update and routine-first assertions passed for v12.0.4");
